name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run -e nodemcu_32

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: .pio/build/nodemcu_32/firmware.bin
